//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "shangdi", table_name = "community_service")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub address: Option<String>,
    pub phone: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub latitude: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub longitude: Option<f32>,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
