//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "detail_meal")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub r#type: Option<String>,
    pub date_time: Option<String>,
    pub meal_info: Option<Json>,
    pub belong_to: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
