//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "health_guide_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub type_name: Option<String>,
    pub icon: Option<i32>,
    pub type_sum: Option<i32>,
    pub type_one: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
