//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::community_service::Entity as CommunityService;
pub use super::detail_meal::Entity as DetailMeal;
pub use super::dinner_provider::Entity as DinnerProvider;
pub use super::feedback::Entity as Feedback;
pub use super::health_guide_content::Entity as HealthGuideContent;
pub use super::health_guide_type::Entity as HealthGuideType;
pub use super::medical_service::Entity as MedicalService;
pub use super::notice::Entity as Notice;
pub use super::policy_file::Entity as PolicyFile;
pub use super::policy_type::Entity as PolicyType;
pub use super::resource_service::Entity as ResourceService;
pub use super::service_map_content::Entity as ServiceMapContent;
pub use super::service_map_type::Entity as ServiceMapType;
pub use super::slideshow::Entity as Slideshow;
pub use super::user::Entity as User;
