//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::communityservice::Entity as Communityservice;
pub use super::detail_meal::Entity as DetailMeal;
pub use super::dinnerprovider::Entity as Dinnerprovider;
pub use super::feedback::Entity as Feedback;
pub use super::health_guide_content::Entity as HealthGuideContent;
pub use super::health_guide_type::Entity as HealthGuideType;
pub use super::medicalservice::Entity as Medicalservice;
pub use super::notice::Entity as Notice;
pub use super::policy_file::Entity as PolicyFile;
pub use super::policy_type::Entity as PolicyType;
pub use super::resourceservice::Entity as Resourceservice;
pub use super::service_map_content::Entity as ServiceMapContent;
pub use super::service_map_type::Entity as ServiceMapType;
pub use super::slideshow::Entity as Slideshow;
pub use super::user::Entity as User;
