//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "shangdi", table_name = "service_map_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub community_name: Option<String>,
    pub type_sum: Option<i32>,
    pub type_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
